#World config
#Fri Jan 23 20:01:23 CET 2026
dailyLoss=10
damage=0
energyAtStart=70
grassProfit=30
height=20
lasting=0
length=5
lossDueToReproduction=25
maximumMutations=2
minimumMutations=0
minimumToReproduce=50
numberAtStart=40
numberOfGrass=50
numberOfGrassSpawn=25
probability=0.0
width=20
