#Default world config
#Fri Jan 23 19:55:09 CET 2026
dailyLoss=10
damage=20
energyAtStart=70
grassProfit=30
height=10
lasting=3
length=5
lossDueToReproduction=25
maximumMutations=2
minimumMutations=0
minimumToReproduce=50
numberAtStart=10
numberOfGrass=15
numberOfGrassSpawn=10
probability=0.05
width=10
