#World config
#Fri Jan 23 20:00:26 CET 2026
dailyLoss=10
damage=20
energyAtStart=70
grassProfit=30
height=5
lasting=3
length=5
lossDueToReproduction=25
maximumMutations=2
minimumMutations=0
minimumToReproduce=50
numberAtStart=2
numberOfGrass=5
numberOfGrassSpawn=2
probability=0.05
width=5
